import { defineConfig } from "vitepress";
import markdownItFootnote from "markdown-it-footnote";

const description = "Add a transient prompt to your zsh command line";
const title = "zsh-transient-prompt";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  head: [
    // favicon generated by https://realfavicongenerator.net/
    [
      "link",
      {
        rel: "icon",
        type: "image/png",
        href: "/favicon-96x96.png",
        sizes: "96x96",
      },
    ],
    [
      "icon",
      {
        rel: "shortcut icon",
        type: "image/svg+xml",
        href: "/favicon.svg",
      },
    ],
    [
      "link",
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
      },
    ],
    [
      "link",
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
      },
    ],
    [
      "meta",
      {
        name: "apple-mobile-web-app-title",
        content: "zsh-transient-prompt",
      },
    ],
    [
      "link",
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
    ],

    // social metas
    ["meta", { property: "og:title", content: "zsh-transient-prompt" }],
    [
      "meta",
      {
        property: "og:description",
        content: description,
      },
    ],
    [
      "meta",
      {
        property: "og:url",
        content: "https://zsh-transient-prompt.olets.dev/",
      },
    ],
    ["meta", { property: "og:site_name", content: "zsh-transient-prompt" }],
    ["meta", { property: "og:type", content: "website" }],
    [
      "meta",
      {
        property: "og:image",
        content:
          "https://zsh-transient-prompt.olets.dev/zsh-transient-prompt-card.jpg",
      },
    ],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    ["meta", { name: "twitter:title", content: "zsh-transient-prompt" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    [
      "meta",
      {
        name: "twitter:description",
        content: description,
      },
    ],
    [
      "meta",
      {
        name: "twitter:image",
        content:
          "https://zsh-transient-prompt.olets.dev/zsh-transient-prompt-card.jpg",
      },
    ],

    // Analytics
    [
      "script",
      {
        src: "https://cdn.usefathom.com/script.js",
        "data-site": "SOXBJHZB",
        "data-spa": "auto",
        defer: "true",
      },
    ],
    [
      "script",
      {
        src: "/js/analytics.js",
      },
    ],

    // Font
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },
    ],
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossorigin: "true",
      },
    ],
    [
      "link",
      {
        href: "https://fonts.googleapis.com/css2?family=Fira+Code&display=swap",
        rel: "stylesheet",
      },
    ],
  ],
  title: title,
  description: description,
  // https://vitepress.dev/reference/site-config#titletemplate
  titleTemplate: `:title :: ${title}`, // to change delimiter from default pipe to play nice with Fathom event id format. see also homepage frontmatter
  // https://vitepress.dev/reference/default-theme-last-updated
  lastUpdated: true,
  markdown: {
    externalLinks: {
      class: "vp-external-link-icon",
      target: "_self",
    },
    config: (md) => {
      md.use(markdownItFootnote);
    },
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  srcExclude: ["vitepressignore"],
  sitemap: {
    hostname: "https://zsh-transient-prompt.olets.dev",
  },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config

    editLink: {
      pattern:
        "https://github.com/olets/zsh-transient-prompt/tree/main/docs/:path",
    },

    logo: "/images/zsh-transient-prompt-logo.jpg",

    nav: [
      {
        text: "Source, Changelog, License",
        link: "https://github.com/olets/zsh-transient-prompt/",
        target: "_self",
      },
      {
        text: "olets.dev",
        link: "https://olets.dev",
        target: "_self",
      },
    ],

    search: {
      provider: "local",
    },

    sidebar: [
      { text: "Overview", link: "/" },
      { text: "Installation", link: "/installation" },
      { text: "Usage", link: "/usage" },
      { text: "Configuration", link: "/configuration" },
      {
        text: "Examples",
        collapsed: false,
        items: [
          {
            text: "Basic",
            link: "/examples/basic",
          },
          {
            text: "Basic Git-aware",
            link: "/examples/basic-git-aware",
          },
          {
            text: "Enhance a 3rd-party theme",
            link: "/examples/enhance-a-3rd-party-theme",
          },
          {
            text: "Advanced Git-aware",
            link: "/examples/advanced-git-aware",
          },
        ],
      },
      { text: "Acknowledgments", link: "/acknowledgments" },
      { text: "Contributing", link: "/contributing" },
    ],
  },
});
